daftar_penyakit = [
    "Gastritis",
    "Dispepsia",
    "Kanker Lambung",
    "GERD",
    "Gastroenteritis",
    "Gastroparesis",
    "Tukak Lambung",
]
daftar_gejala = [
    [
        "y",
        "y",
        "y",
        "y",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
        "n",
        "n",
    ],  # Gastritis
    [
        "y",
        "y",
        "n",
        "y",
        "y",
        "y",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
        "n",
    ],  # Dispepsia
    [
        "n",
        "n",
        "y",
        "y",
        "n",
        "n",
        "y",
        "y",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
        "n",
        "n",
        "n",
    ],  # Kanker Lambung
    [
        "y",
        "y",
        "n",
        "y",
        "n",
        "n",
        "n",
        "n",
        "y",
        "y",
        "n",
        "y",
        "n",
        "n",
        "n",
        "n",
        "y",
    ],  # GERD
    [
        "y",
        "n",
        "n",
        "y",
        "n",
        "y",
        "n",
        "n",
        "y",
        "y",
        "n",
        "y",
        "n",
        "n",
        "n",
        "y",
        "n",
    ],  # Gastroenteritis
    [
        "n",
        "y",
        "y",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
        "y",
        "n",
        "y",
        "n",
        "y",
        "n",
        "n",
        "n",
    ],  # Gastroparesis
    [
        "y",
        "n",
        "y",
        "y",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "y",
        "n",
        "n",
    ],  # Tukak Lambung
]

pertanyaan = [
    "Apakah kamu merasakan perih pada lambung? ",
    "Apakah perut kamu terasa kembung? ",
    "Apakah nafsu makan kamu berkurang? ",
    "Apakah kamu merasa mual? ",
    "Apakah kamu sembelit? ",
    "Apakah kamu diare? ",
    "Apakah berat badan kamu menurun? ",
    "Apakah BAB kamu berwarna hitam? ",
    "Apakah kamu demam? ",
    "Apakah rasa makanan kembali ? ",
    "Apakah BAB kamu cair? ",
    "Apakah kamu merasakan kejang di perut? ",
    "Apakah kamu merasa nyeri pada uluh hati? ",
    "Apakah kamu merasakan perasaan kenyang yang berlebihan? ",
    "Apakah kamu merasa nyeri pada tukak lambung? ",
    "Apakah kamu muntah? ",
    "Apakah kamu merasa terbakar dibagian dada (heartburn)? ",
]

daftar_deskripsi = [
    "Gastritis adalah peradangan pada dinding lambung. Ini bukanlah penyakit, namun sebuah kondisi yang disebabkan oleh beragam faktor yang berbeda, seperti konsumsi alkohol berlebihan, stres, muntah-muntah yang kronis, atau obat-obatan tertentu. Infeksi, refluks empedu, bakteri, dan anemia pernikus juga penyebab umum dari gastritis lainnya.",
    "Sindrom dispepsia merupakan kumpulan gejala yang muncul dan dapat menimbulkan ketidaknyaman pada perut bagian atas. Gejala yang dirasakan biasanya sakit perut dan kembung. Dispepsia dapat terjadi pada setiap orang.",
    "Kanker lambung adalah penyakit yang terjadi karena pertumbuhan sel lambung secara abnormal dan tak terkendali. Pertumbuhan sel abnormal ini terjadi karena sel mengalami perubahan genetik.",
    "Penyakit asam lambung atau gastroesophageal reflux disease (GERD) adalah munculnya rasa terbakar di dada akibat asam lambung naik ke kerongkongan. Gejala penyakit asam lambung muncul minimal 2 kali dalam seminggu. ",
    "Flu perut atau gastroenteritis adalah muntah dan diare akibat infeksi atau peradangan pada dinding saluran pencernaan, terutama lambung dan usus. Di masyarakat luas, gastroenteritis lebih dikenal dengan istilah muntaber.",
    "Gastroparesis adalah gangguan pada otot lambung yang menyebabkan gerakan lambung untuk mendorong makanan ke usus menjadi lebih lambat. Gastroparesis ditandai dengan gejala berupa mual, muntah, dan mudah merasa kenyang. Penyebab gastroparesis belum diketahui dengan pasti, tetapi diduga disebabkan oleh kerusakan saraf yang mengatur gerakan otot lambung, yaitu saraf vagus. Saraf ini dapat mengalami kerusakan akibat berbagai hal, misalnya komplikasi operasi pada lambung atau komplikasi diabetes.",
    "Tukak lambung adalah luka pada lambung yang menyebabkan keluhan sakit maag. Selain di lambung, luka tersebut dapat terbentuk di usus 12 jari atau di bagian bawah kerongkongan.",
]
